ROOT=.
FWDIR:=$(ROOT)/firmware
BINDIR=$(ROOT)/bin
SRCDIR=$(ROOT)/src
INCDIR=$(ROOT)/include
CEXTS:=c
ASMEXTS:=s S
CXXEXTS:=cpp c++ cc
WARNFLAGS+=-Wall -Wextra -Wno-unused-parameter
EXTRA_CFLAGS=
EXTRA_CXXFLAGS=
USE_PACKAGE:=1
EXCLUDE_COLD_LIBRARIES:=
IS_LIBRARY:=0
.DEFAULT_GOAL=quick
-include ./common.mk
