# CMake generated Testfile for 
# Source directory: C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests
# Build directory: C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[log_preparation]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/prepare_dynamics_test.py" "--calibrate" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/nexus_calibrate.exe")
  set_tests_properties([=[log_preparation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;21;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[log_preparation]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/prepare_dynamics_test.py" "--calibrate" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/nexus_calibrate.exe")
  set_tests_properties([=[log_preparation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;21;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[log_preparation]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/prepare_dynamics_test.py" "--calibrate" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/nexus_calibrate.exe")
  set_tests_properties([=[log_preparation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;21;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[log_preparation]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/prepare_dynamics_test.py" "--calibrate" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/nexus_calibrate.exe")
  set_tests_properties([=[log_preparation]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;21;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[log_preparation]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[odometry_trace_log]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/odometry_trace_log_test.py")
  set_tests_properties([=[odometry_trace_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;22;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[odometry_trace_log]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/odometry_trace_log_test.py")
  set_tests_properties([=[odometry_trace_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;22;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[odometry_trace_log]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/odometry_trace_log_test.py")
  set_tests_properties([=[odometry_trace_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;22;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[odometry_trace_log]=] "C:/Python314/python.exe" "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/odometry_trace_log_test.py")
  set_tests_properties([=[odometry_trace_log]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;22;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[odometry_trace_log]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[estimator]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/estimator_test.exe")
  set_tests_properties([=[estimator]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[estimator]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/estimator_test.exe")
  set_tests_properties([=[estimator]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[estimator]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/estimator_test.exe")
  set_tests_properties([=[estimator]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[estimator]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/estimator_test.exe")
  set_tests_properties([=[estimator]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[estimator]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[controller]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/controller_test.exe")
  set_tests_properties([=[controller]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[controller]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/controller_test.exe")
  set_tests_properties([=[controller]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[controller]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/controller_test.exe")
  set_tests_properties([=[controller]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[controller]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/controller_test.exe")
  set_tests_properties([=[controller]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[controller]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/calibration_test.exe")
  set_tests_properties([=[calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/calibration_test.exe")
  set_tests_properties([=[calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/calibration_test.exe")
  set_tests_properties([=[calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/calibration_test.exe")
  set_tests_properties([=[calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[calibration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[system]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/system_test.exe")
  set_tests_properties([=[system]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[system]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/system_test.exe")
  set_tests_properties([=[system]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[system]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/system_test.exe")
  set_tests_properties([=[system]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[system]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/system_test.exe")
  set_tests_properties([=[system]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[system]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[autonomous_units]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/autonomous_units_test.exe")
  set_tests_properties([=[autonomous_units]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[autonomous_units]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/autonomous_units_test.exe")
  set_tests_properties([=[autonomous_units]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[autonomous_units]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/autonomous_units_test.exe")
  set_tests_properties([=[autonomous_units]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[autonomous_units]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/autonomous_units_test.exe")
  set_tests_properties([=[autonomous_units]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[autonomous_units]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[driver_input]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/driver_input_test.exe")
  set_tests_properties([=[driver_input]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[driver_input]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/driver_input_test.exe")
  set_tests_properties([=[driver_input]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[driver_input]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/driver_input_test.exe")
  set_tests_properties([=[driver_input]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[driver_input]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/driver_input_test.exe")
  set_tests_properties([=[driver_input]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[driver_input]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[automatic_calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/automatic_calibration_test.exe")
  set_tests_properties([=[automatic_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[automatic_calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/automatic_calibration_test.exe")
  set_tests_properties([=[automatic_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[automatic_calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/automatic_calibration_test.exe")
  set_tests_properties([=[automatic_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[automatic_calibration]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/automatic_calibration_test.exe")
  set_tests_properties([=[automatic_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[automatic_calibration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[calibration_routine]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/calibration_routine_test.exe")
  set_tests_properties([=[calibration_routine]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[calibration_routine]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/calibration_routine_test.exe")
  set_tests_properties([=[calibration_routine]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[calibration_routine]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/calibration_routine_test.exe")
  set_tests_properties([=[calibration_routine]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[calibration_routine]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/calibration_routine_test.exe")
  set_tests_properties([=[calibration_routine]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[calibration_routine]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[mechanism]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/mechanism_test.exe")
  set_tests_properties([=[mechanism]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[mechanism]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/mechanism_test.exe")
  set_tests_properties([=[mechanism]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[mechanism]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/mechanism_test.exe")
  set_tests_properties([=[mechanism]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[mechanism]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/mechanism_test.exe")
  set_tests_properties([=[mechanism]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[mechanism]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[arm_motion]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/arm_motion_test.exe")
  set_tests_properties([=[arm_motion]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[arm_motion]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/arm_motion_test.exe")
  set_tests_properties([=[arm_motion]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[arm_motion]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/arm_motion_test.exe")
  set_tests_properties([=[arm_motion]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[arm_motion]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/arm_motion_test.exe")
  set_tests_properties([=[arm_motion]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[arm_motion]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[startup]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/startup_test.exe")
  set_tests_properties([=[startup]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[startup]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/startup_test.exe")
  set_tests_properties([=[startup]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[startup]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/startup_test.exe")
  set_tests_properties([=[startup]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[startup]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/startup_test.exe")
  set_tests_properties([=[startup]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;28;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[startup]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[chassis_adapter]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Debug/chassis_adapter_test.exe")
  set_tests_properties([=[chassis_adapter]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;34;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[chassis_adapter]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/Release/chassis_adapter_test.exe")
  set_tests_properties([=[chassis_adapter]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;34;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[chassis_adapter]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/MinSizeRel/chassis_adapter_test.exe")
  set_tests_properties([=[chassis_adapter]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;34;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[chassis_adapter]=] "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/.test-build-calibration-audit/RelWithDebInfo/chassis_adapter_test.exe")
  set_tests_properties([=[chassis_adapter]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;34;add_test;C:/Users/rugge/Documents/vex-vscode-projects/SX_SAWP/tests/CMakeLists.txt;0;")
else()
  add_test([=[chassis_adapter]=] NOT_AVAILABLE)
endif()
